/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package github.actions.gradle.sample2;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
